// <auto-generated />
using System;
using ITAssetManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITAssetManagement.Models.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251223033755_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITAssetManagement.Models.Entitis.Asset", b =>
                {
                    b.Property<int>("AssetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetID"));

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("AssetTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Config")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("QRCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Serial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierID")
                        .HasColumnType("int");

                    b.HasKey("AssetID");

                    b.HasIndex("AssetTypeID");

                    b.HasIndex("Serial")
                        .IsUnique()
                        .HasFilter("[Serial] IS NOT NULL");

                    b.HasIndex("Status");

                    b.HasIndex("SupplierID");

                    b.ToTable("Asset", (string)null);
                });

            modelBuilder.Entity("ITAssetManagement.Models.Entitis.AssetAllocation", b =>
                {
                    b.Property<int>("AllocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllocationID"));

                    b.Property<DateTime>("AllocatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssetID")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AllocationID");

                    b.HasIndex("AssetID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("UserID");

                    b.ToTable("AssetAllocation", (string)null);
                });

            modelBuilder.Entity("ITAssetManagement.Models.Entitis.AssetType", b =>
                {
                    b.Property<int>("AssetTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetTypeID"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AssetTypeID");

                    b.ToTable("AssetType", (string)null);
                });

            modelBuilder.Entity("ITAssetManagement.Models.Entitis.AuditLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordID")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("UserID");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("ITAssetManagement.Models.Entitis.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ManagerID")
                        .HasColumnType("int");

                    b.HasKey("DepartmentID");

                    b.HasIndex("ManagerID")
                        .IsUnique()
                        .HasFilter("[ManagerID] IS NOT NULL");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("ITAssetManagement.Models.Entitis.InventoryCheck", b =>
                {
                    b.Property<int>("CheckID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckID"));

                    b.Property<int?>("ActualStatus")
                        .HasColumnType("int");

                    b.Property<int>("AssetID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discrepancy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CheckID");

                    b.HasIndex("AssetID");

                    b.HasIndex("UserID");

                    b.ToTable("InventoryCheck", (string)null);
                });

            modelBuilder.Entity("ITAssetManagement.Models.Entitis.RepairTicket", b =>
                {
                    b.Property<int>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketID"));

                    b.Property<int>("AssetID")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RepairDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReplacedAssetID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("TicketID");

                    b.HasIndex("AssetID");

                    b.HasIndex("ReplacedAssetID");

                    b.HasIndex("UserID");

                    b.ToTable("RepairTicket", (string)null);
                });

            modelBuilder.Entity("ITAssetManagement.Models.Entitis.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierID"));

                    b.Property<string>("Contact")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SupplierID");

                    b.ToTable("Supplier", (string)null);
                });

            modelBuilder.Entity("ITAssetManagement.Models.Entitis.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("ITAssetManagement.Models.Entitis.WarehouseTransaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<int>("AssetID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("TransactionID");

                    b.HasIndex("AssetID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("UserID");

                    b.ToTable("WarehouseTransaction", (string)null);
                });

            modelBuilder.Entity("ITAssetManagement.Models.Entitis.Asset", b =>
                {
                    b.HasOne("ITAssetManagement.Models.Entitis.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetManagement.Models.Entitis.Supplier", "Supplier")
                        .WithMany("Assets")
                        .HasForeignKey("SupplierID");

                    b.Navigation("AssetType");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ITAssetManagement.Models.Entitis.AssetAllocation", b =>
                {
                    b.HasOne("ITAssetManagement.Models.Entitis.Asset", "Asset")
                        .WithMany("AssetAllocations")
                        .HasForeignKey("AssetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetManagement.Models.Entitis.Department", "Department")
                        .WithMany("AssetAllocations")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetManagement.Models.Entitis.User", "User")
                        .WithMany("AssetAllocations")
                        .HasForeignKey("UserID");

                    b.Navigation("Asset");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ITAssetManagement.Models.Entitis.AuditLog", b =>
                {
                    b.HasOne("ITAssetManagement.Models.Entitis.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ITAssetManagement.Models.Entitis.Department", b =>
                {
                    b.HasOne("ITAssetManagement.Models.Entitis.User", "Manager")
                        .WithOne("ManagedDepartment")
                        .HasForeignKey("ITAssetManagement.Models.Entitis.Department", "ManagerID");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("ITAssetManagement.Models.Entitis.InventoryCheck", b =>
                {
                    b.HasOne("ITAssetManagement.Models.Entitis.Asset", "Asset")
                        .WithMany("InventoryChecks")
                        .HasForeignKey("AssetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetManagement.Models.Entitis.User", "User")
                        .WithMany("InventoryChecks")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ITAssetManagement.Models.Entitis.RepairTicket", b =>
                {
                    b.HasOne("ITAssetManagement.Models.Entitis.Asset", "Asset")
                        .WithMany("RepairTickets")
                        .HasForeignKey("AssetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetManagement.Models.Entitis.Asset", "ReplacedAsset")
                        .WithMany()
                        .HasForeignKey("ReplacedAssetID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ITAssetManagement.Models.Entitis.User", "User")
                        .WithMany("RepairTickets")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("ReplacedAsset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ITAssetManagement.Models.Entitis.WarehouseTransaction", b =>
                {
                    b.HasOne("ITAssetManagement.Models.Entitis.Asset", "Asset")
                        .WithMany("WarehouseTransactions")
                        .HasForeignKey("AssetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetManagement.Models.Entitis.Department", "Department")
                        .WithMany("WarehouseTransactions")
                        .HasForeignKey("DepartmentID");

                    b.HasOne("ITAssetManagement.Models.Entitis.User", "User")
                        .WithMany("WarehouseTransactions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ITAssetManagement.Models.Entitis.Asset", b =>
                {
                    b.Navigation("AssetAllocations");

                    b.Navigation("InventoryChecks");

                    b.Navigation("RepairTickets");

                    b.Navigation("WarehouseTransactions");
                });

            modelBuilder.Entity("ITAssetManagement.Models.Entitis.AssetType", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("ITAssetManagement.Models.Entitis.Department", b =>
                {
                    b.Navigation("AssetAllocations");

                    b.Navigation("WarehouseTransactions");
                });

            modelBuilder.Entity("ITAssetManagement.Models.Entitis.Supplier", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("ITAssetManagement.Models.Entitis.User", b =>
                {
                    b.Navigation("AssetAllocations");

                    b.Navigation("AuditLogs");

                    b.Navigation("InventoryChecks");

                    b.Navigation("ManagedDepartment");

                    b.Navigation("RepairTickets");

                    b.Navigation("WarehouseTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
